# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title : Kevin Pfefferle
email: kevin@pfefferle.co
description: > # this means to ignore newlines until "baseurl:"
  Double Agent 0012 at <a href="http://testdouble.com">Test Double</a>.<br>
  Maker, thinker, rationalist.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kevin.pfefferle.co" # the base hostname & protocol for your site
twitter_username: kpfefferle
github_username:  kpfefferle

permalink: /:year/:month/:day/:title

# Build settings
markdown: kramdown
highlighter: rouge
